"""initial schema

Revision ID: a74b9a10cd37
Revises: 
Create Date: 2026-03-02 14:42:31.815970

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a74b9a10cd37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('home_city', sa.String(length=255), nullable=False),
    sa.Column('preference_vector', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('geo', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('price_tier', sa.Integer(), nullable=False),
    sa.Column('is_open_now', sa.Boolean(), nullable=False),
    sa.Column('live_busyness', sa.Float(), nullable=True),
    sa.Column('last_signal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geo', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('geo_accuracy', sa.Float(), nullable=False),
    sa.Column('time_of_day', sa.String(length=50), nullable=False),
    sa.Column('day_type', sa.Enum('WEEKDAY', 'WEEKEND', 'HOLIDAY', name='daytype'), nullable=False),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('weather_temp', sa.Float(), nullable=True),
    sa.Column('weather_precip_probability', sa.Float(), nullable=True),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('intent_declared', sa.String(length=100), nullable=True),
    sa.Column('energy_inferred', sa.Enum('LOW', 'MODERATE', 'HIGH', name='energylevel'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PRESENCE', 'SOCIAL_RELAY', 'ENVIRONMENTAL', 'BEHAVIORAL', 'AMBIENT', name='signaltype'), nullable=False),
    sa.Column('source_user_id', sa.UUID(), nullable=True),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('emitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geo', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_a', sa.UUID(), nullable=False),
    sa.Column('user_b', sa.UUID(), nullable=False),
    sa.Column('edge_weight', sa.Float(), nullable=False),
    sa.Column('mutual', sa.Boolean(), nullable=False),
    sa.Column('established_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_interaction', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_overlap_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trust_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_user_id', sa.UUID(), nullable=False),
    sa.Column('target_venue_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('contributing_signals', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('network_depth', sa.Integer(), nullable=False),
    sa.Column('decay_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('context_state_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('surfaced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acted_on', sa.Boolean(), nullable=False),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['context_state_id'], ['context_states.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('context_state_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('trust_attribution', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('primary_signal_id', sa.UUID(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('eta_minutes', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['context_state_id'], ['context_states.id'], ),
    sa.ForeignKeyConstraint(['primary_signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunities')
    op.drop_table('moments')
    op.drop_table('trust_scores')
    op.drop_table('social_edges')
    op.drop_table('signals')
    op.drop_table('context_states')
    op.drop_table('venues')
    op.drop_table('users')
    # ### end Alembic commands ###
